### ISSUE TITLE
Bepalen of we BGT-grenzen of bestemmingsgrenzen gebruiken + rol kadastrale grenzen

### ISSUE THREAD

**Issue by DevlinOosterwijk** [IDgis/Oldenzaal#1]

**Comment by HermanAssink** [comment]
En welke rol kadastrale grenzen moeten spelen

**Comment by Michiel-2** [comment]
De BGT is altijd bijgehouden en vormt de basisregistratie.

Sinds 1 juli 2017 is de BGT voor de gemeente Oldenzaal verplicht als kaartonderlegger.

De BGT wordt ook de basis voor de 3d object registratie SOR.

De kadastrale kaart is niet meer actueel, maar dient als check/achtervang.

Het beleidsarm overzetten van bestemmingsplannen moet eveneens een check vormen.

Je hebt een feitelijke werkelijkheid en een juridische werkelijkheid. Daar moet een safe ingebouwd worden. We willen burenrecht beschermen.

De pilot is bedoeld om overlap en afwijkingen in beeld te krijgen en ook duidelijk te krijgen of de afwijkingen een muis of een olifant vormen.
